// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infrastructure.persistence;

#nullable disable

namespace k8api.Migrations
{
    [DbContext(typeof(LocaldbContext))]
    partial class LocaldbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84e88a13-fa68-4eff-b622-bc0a4f625099"),
                            Name = "Prod I - A",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = new Guid("2c1d4256-cafd-4f1f-a50f-dc345675a559"),
                            Name = "Prod I - B",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = new Guid("bfebbd3c-cf5d-43c2-8fbd-96b5b9a6f18e"),
                            Name = "Prod II",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("edeaa402-a87f-4b3b-8a27-092505f199be"),
                            Name = "Prod III",
                            Price = 79.00m
                        },
                        new
                        {
                            Id = new Guid("1bb52325-de91-4c9e-b7ad-c21139ee52f0"),
                            Name = "Prod III - B",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = new Guid("4b3459ce-1da0-4741-b1c4-55715228b5ff"),
                            Name = "Prod IV - A",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = new Guid("7eb56574-27fe-4bc6-9b4c-e3553fb5e072"),
                            Name = "Prod V",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = new Guid("4b10621a-bb5a-42da-9d1d-54f277190670"),
                            Name = "Prod VI",
                            Price = 199.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
